### PR TITLE
EIG fix + info changes

### LINKED ISSUE #10353: Extreme Industrial Greenhouse power usage
### Your GTNH Discord Username

pulsemageadvocate

### Your Pack Version

2.1.2.4-pre-dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Extreme Industrial Greenhouse with 2 UV Energy Hatches consume energy equal to 1 UHV Energy Hatch.

### The Reality

1x UHV Energy Hatch

2x UV Energy Hatches

### Your Proposal

Fix power usage?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by kuba6000**
**Extreme Industrial Greenhouse**
Fixed https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10353
Also made some visual changes:
image
**Percentages shows the progress of dropping items.**
image
image

### CODE REVIEW

File: src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java [hunk 1]
```diff
@@ -604,6 +630,9 @@ public void GreenHouseSlotIC2(GT_TileEntity_ExtremeIndustrialGreenhouse tileEnti
                     }
                     if (st.length == 0)
                         continue;
+                    for(ItemStack s : st)
+                        if(s == null)
```
Comment (repo-alt) [inline src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java:632]: When is that possible, and won't we get in the endless loop here? (that whole cycle looks weird tbh, with that  --i above)

Comment (kuba6000) [reply src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java:632]: I don't remember why the i-- was there, removed it. The gain is returning null with stonelilys, because the class checks block under the crop (https://github.com/GTNewHorizons/Crops-plus-plus/blob/master/src/main/java/com/github/bartimaeusnek/cropspp/crops/gregtechCrops/StonelillyCrop.java#L185).
I will work on that later.

Comment (repo-alt) [reply src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java:632]: so, if one of the stacks returned by the harvest_automated is null, we try again, why?
also, how we won't get in the endless cycle here as well?
I mean, which crops do legitimately return nulls in their drop list?

Comment (kuba6000) [reply src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java:632]: The loop is going through only 10 times, there is only continue statement.

Comment (kuba6000) [reply src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java:632]: No crop should return null in getGain method, the harvest_automated calls getGain random amount of times. We are making 10 generations to get that randomness feeling without needing to spawn crop every time to get drops.

For now I'm just adding the check for stonelilys, later I will work on under crops block support in "planting crops" process

**Review by repo-alt — APPROVED** [review]
