### PR TITLE
Fix accidental nerf to circuit assembler

### LINKED ISSUE #10709: Crystalcomputer and Wetware Assembly use the wrong amount of circuits in expensive recipe
### Your GTNH Discord Username

xSkewer#4113

### Your Pack Version

2.1.2.4-dev17

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I expected these circuits to use 12 of the previous step in their non-CAL expensive recipe.

### The Reality

They don't
image
image

These are both ZPM circuits if that means anything.

### Your Proposal

Increase previous circuit count to 12.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by miozune**
And minor cleanup
2x circuits is intended recipe
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10709
See also: https://github.com/GTNewHorizons/bartworks/pull/94

### CODE REVIEW

File: src/main/java/com/github/bartimaeusnek/bartworks/system/material/CircuitGeneration/CircuitImprintLoader.java [hunk 1]
```diff
@@ -117,17 +117,7 @@ private static String getTypeFromOreDict(ItemStack[] outputs) {
...
-        if (oreIDS.length < 1)
-            return false;
-        
-        for (int oreID : oreIDS) {
-            if (OreDictionary.getOreName(oreID).contains("Circuit") || OreDictionary.getOreName(oreID).contains("circuit"))
-                return true;
-        }
-
-        return false;
+        return BW_Util.getOreNames(item).stream().anyMatch(s -> s.contains("Circuit") || s.contains("circuit"));
```
Comment (GlodBlock) [inline src/main/java/com/github/bartimaeusnek/bartworks/system/material/CircuitGeneration/CircuitImprintLoader.java]: some circuit parts like smd resistance also have 'cricuit' in their oredict name. will they be considered as circuits?

Comment (miozune) [reply src/main/java/com/github/bartimaeusnek/bartworks/system/material/CircuitGeneration/CircuitImprintLoader.java]: Small Coil and normal SMD Resistor and Inductor have oredict. SMD Resistor is used up to nano. Small Coil and SMD Inductor are properly multiplied, though not sure why. So they're working fine... for now.
Sure they will be broken in the future, so I'll use `getCircuitTierFromOreDictName` instead.

**Review by GlodBlock — APPROVED** [review]
