### PR TITLE
EIG: Fix stocking input bus exploit

### LINKED ISSUE #11768: Extreme Industrial Greenhouse does not respect max stack sizes with Stocking ME Bus
### Your GTNH Discord Username

Yin#0001

### Your Pack Version

2.2.3

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

Extreme Industrial greenhouse should allow 64 seeds per slot in normal mode.

### The Reality

Using the Stocking ME Bus, I am able to insert as many seeds into one slot as I want.

Expected: http://yin.systems/2022/10/2022-10-30_22-41-43_CReV.png
Bug: http://yin.systems/2022/10/2022-10-30_22-41-58_974r.png
Bug 2: http://yin.systems/2022/10/2022-10-30_22-42-48_4LDK.png

### Your Proposal

One stack of seeds per slot as intended.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by kuba6000**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11768

### CODE REVIEW

File: src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java [hunk 1]
```diff
@@ -746,7 +746,9 @@ public GreenHouseSlot(
 
             crop = b;
             isIC2Crop = false;
-            if (addDrops(world, input.stackSize, autocraft) == 0 && !drops.isEmpty()) {
+            int toUse = Math.min(64, input.stackSize);
```
Comment (minecraft7771) [inline src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java:749]: Wouldn't it be cleaner to use `input.getMaxStackSize()` instead of hard coded 64?

File: src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java [hunk 2]
```diff
@@ -563,14 +565,12 @@ public ITexture[] getTexture(
     public boolean addCrop(ItemStack input) {
         if (!isIC2Mode)
             for (GreenHouseSlot g : mStorage)
-                if (GT_Utility.areStacksEqual(g.input, input)) {
+                if (g.input.stackSize < 64 && GT_Utility.areStacksEqual(g.input, input)) {
```
Comment (minecraft7771) [inline src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java:568]: We should also use the max stack size getter here too imo.

**Review by minecraft7771 — CHANGES_REQUESTED** [review]

File: src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java (hunk 1 above)
Comment (kuba6000) [reply src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java:749]: No, the slots in multi holds 64

Comment (kuba6000) [reply src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java:749]: So they will be added in the next iteration to the same slot anyway

Comment (minecraft7771) [reply src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java:749]: I see

**Review by minecraft7771 — APPROVED** [review]

**Comment by xSkewer** [comment]
Getting an already tesselating crash with the rendering changes on existing EIGs. Have not tested newly placed EIGs.

**Comment by kuba6000** [comment]
> Getting an already tesselating crash with the rendering changes on existing EIGs. Have not tested newly placed EIGs.

Will fix
